# Generated by Django 3.2.5 on 2021-07-31 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default=0, related_name='lided_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
